### ISSUE TITLE
Published package doesn't include src folder

### ISSUE THREAD

**Issue by LukasDeco** [jihchi/res-msw#7]
Hey! We installed it and it doesn't include the src folder. We get this error on bsb -make-world
```
\node_modules/res-msw/src: No such file or directory\
```

bs-platform 8.4

**Comment by jihchi** [comment]
I've fixed it and published [v5.0.1](https://github.com/jihchi/res-msw/releases/tag/v0.5.1).

Please let me know if there is any issues.

Thank you @LukasDeco !
